const NAV = [
  ['dashboard','Dashboard','DB'],['copilot','AI Factory Copilot','AI'],['digital','Digital Twin','DT'],['machines','Machine Monitoring','MC'],
  ['maintenance','Predictive Maintenance','PM'],['production','Production Management','PR'],['vision','AI Vision','CV'],['quality','Quality Control','QC'],
  ['workers','Worker Management','WK'],['energy','Energy Management','EN'],['sustainability','Sustainability','ES'],['inventory','Inventory','IN'],
  ['alerts','Alerts Center','AL'],['analytics','Analytics','AN'],['reports','Reports','RP'],['loss','Cost Loss Analyzer','CL'],['health','Factory Health','FH'],
  ['users','User Management','UM'],['settings','Factory Settings','ST']
];
const ROLE_ACCESS = {
  'Factory Owner': NAV.map(n=>n[0]),
  'Admin': NAV.map(n=>n[0]).filter(n=>n!=='users'),
  'Production Manager': ['dashboard','digital','machines','production','quality','workers','alerts','analytics','reports','health'],
  'Maintenance Engineer': ['dashboard','digital','machines','maintenance','energy','alerts','reports','health','settings'],
  'Supervisor': ['dashboard','digital','machines','production','vision','quality','workers','alerts','reports'],
  'Operator': ['dashboard','digital','machines','vision','alerts'],
  'Quality Inspector': ['dashboard','vision','quality','alerts','analytics','reports']
};
const statusLabel = {running:'Running', idle:'Idle', maintenance:'Maintenance', offline:'Offline', critical:'Critical'};
const app = document.getElementById('app');
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const fmt=n=>Number(n).toLocaleString('en-IN');
const rnd=(a,b)=>a+Math.random()*(b-a);
const pick=a=>a[Math.floor(Math.random()*a.length)];
const nowTime=()=>new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', second:'2-digit'});

const state = {
  theme: localStorage.getItem('factoryos-theme') || 'dark',
  authed: localStorage.getItem('factoryos-auth') === '1',
  authMode: 'login', route: 'dashboard', role: localStorage.getItem('factoryos-role') || 'Factory Owner', sidebar:false,
  search:'', machineFilter:'all', selectedMachine:'M-04', toast:'', reportType:'Daily Report', reportGenerated:null,
  settings:{factory:'FactoryOS Demo Plant', rate:8.0, shift:'06:00 - 18:00', timezone:'Etc/UTC', language:'English', alertTemp:84, alertVibration:6.0},
  widgets:['production','health','energy','alerts','quality','inventory','revenue','carbon','shift','weather'],
  chat:[{who:'ai', text:'FactoryOS Copilot online. Ask about production, maintenance, energy, quality, inventory, or reports.'}],
  data: createFactoryData()
};
document.documentElement.dataset.theme = state.theme;

function createFactoryData(){
  const names=['CNC Lathe 01','CNC Lathe 02','Drilling Machine','Milling Machine','Grinding Machine','Press Machine','Welding Robot','Paint Booth','Laser Cutter','Packaging Line','Inspection Camera','Compressor','Hydraulic Press','Assembly Cell','Pick Place Robot','Conveyor A','Conveyor B','Injection Molder','Furnace','Water Jet','CNC Router','Polishing Cell','Label Printer','Palletizer','Utilities Pump','Boiler','Cooling Tower','Warehouse Lift','AGV Dock','QA Bench','Soldering Cell','Extruder','Mixer','Robotic Arm','Sorter','Servo Press','Leak Tester','Etching Cell','Finishing Cell','Spare CNC','Vacuum Former','Material Feeder'];
  const sections=['Assembly Line','CNC Area','Packaging','Warehouse','Quality Inspection','Maintenance Room','Utilities','Office'];
  const positions=[[19,24],[48,22],[76,25],[72,51],[23,58],[49,64],[74,72],[57,42],[35,37],[15,73],[41,78],[85,39]];
  const statuses=['running','running','running','running','running','running','idle','maintenance','offline','critical'];
  const machines=Array.from({length:42},(_,i)=>{
    const status=i===3?'critical':i===4?'maintenance':pick(statuses);
    const p=positions[i] || [rnd(12,86), rnd(18,78)];
    const health=status==='critical'?32:status==='maintenance'?58:status==='idle'?76:status==='offline'?62:Math.round(rnd(78,96));
    return {id:`M-${String(i+1).padStart(2,'0')}`, name:names[i%names.length], section:sections[i%sections.length], type:names[i%names.length].split(' ')[0], status,
      x:p[0], y:p[1], temperature: status==='critical'?98:rnd(57,72), vibration: status==='critical'?8.6:rnd(1.1,3.4), rpm:Math.round(rnd(900,2600)), voltage:rnd(410,430), current:rnd(8,46), power: status==='critical'?18.6:rnd(2.8,13.5), runtime:rnd(2,13), downtime:rnd(.1,3.8), utilization:rnd(62,94), health, output:Math.round(rnd(80,560)), failure:100-health+rnd(0,10), history:Array.from({length:22},()=>rnd(52,80)), maint:[`Lubrication completed on 12 Jun`, `Bearing inspection on 28 May`, `Calibration verified on 04 May`]};
  });
  const productionHistory=Array.from({length:16},(_,i)=>Math.round(600+i*70+rnd(-100,180)));
  const energyHistory=Array.from({length:16},(_,i)=>Math.round(420+i*22+rnd(-60,80)));
  const qualityHistory=Array.from({length:16},()=>rnd(94,99.4));
  const inventory=[
    ['Steel Sheets','Raw Material',1210,500,'kg'],['Aluminium Rod','Raw Material',430,300,'kg'],['Bearing 6205','Spare Part',15,50,'pcs'],['Cutting Tool','Spare Part',8,30,'pcs'],['Oil S5','Consumable',61,20,'L'],['Packaging Cartons','Finished Goods',2760,900,'pcs'],['Copper Wire','Raw Material',190,250,'kg'],['Coolant','Consumable',88,45,'L']
  ].map(([name,category,current,min,unit],i)=>({id:i+1,name,category,current,min,unit,supplier:pick(['Tata Steel','Bosch Industrial','Mahindra Logistics','Schneider Electric','Local Vendor A'])}));
  const workers=Array.from({length:18},(_,i)=>({id:i+1,name:['Asha Singh','Rohan Mehta','Imran Khan','Jenna Taylor','Vikram Rao','Neha Jain'][i%6],role:pick(['Operator','Supervisor','Quality Inspector','Maintenance Engineer']),shift:pick(['A','B','C']),status:pick(['On Line','On Line','On Break','Training']),productivity:Math.round(rnd(72,98)),safety:Math.round(rnd(86,100))}));
  const alerts=[
    makeAlert('Machine 04','Critical temperature and vibration detected','critical'),makeAlert('Inventory Low','Bearing 6205 below minimum stock','maintenance'),makeAlert('Energy Usage','High consumption in Line 3','idle'),makeAlert('Quality Issue','Scratch defects trending upward','critical')
  ];
  return {machines, production:12842, target:15000, defects:247, workers, inventory, alerts, productionHistory, energyHistory, qualityHistory, carbon:785, revenue:245000, costLoss:{downtime:42500, energy:18400, defects:31500, maintenance:22000, production:68800}};
}
function makeAlert(title,msg,severity='idle'){return {id:crypto.randomUUID?.()||String(Math.random()), title,msg,severity,time:nowTime(), read:false};}

function tick(){
  const d=state.data;
  d.machines.forEach(m=>{
    if(Math.random()<.012){m.status=pick(['running','running','running','idle','maintenance','offline',m.health<45?'critical':'running']);}
    const target={running:66,idle:55,maintenance:52,offline:39,critical:96}[m.status];
    m.temperature=clamp(m.temperature+(target-m.temperature)*.09+rnd(-.45,.55),28,105);
    const vibTarget={running:2.2,idle:1.1,maintenance:1.5,offline:.2,critical:8.3}[m.status];
    m.vibration=clamp(m.vibration+(vibTarget-m.vibration)*.12+rnd(-.08,.12),0,10);
    m.rpm=Math.round(clamp(m.rpm+(m.status==='running'?rnd(-45,55):rnd(-120,20)),0,3000));
    m.voltage=clamp(m.voltage+rnd(-1.4,1.5),395,440);
    m.current=clamp(m.current+(m.status==='running'?rnd(-1.2,1.5):rnd(-2,.6)),0,55);
    m.power=clamp(m.voltage*m.current/1000*(m.status==='running'?1:.35),0,26);
    if(m.status==='running'){m.runtime+=.04;m.output+=Math.round(rnd(1,6));m.utilization=clamp(m.utilization+rnd(-1,1.4),52,99);} else {m.downtime+=.04;m.utilization=clamp(m.utilization-rnd(.1,1.2),18,91);}
    const stress=(m.temperature-62)*.35+m.vibration*4+(m.runtime/10);
    m.health=clamp(Math.round(m.health - Math.max(0,stress-15)*.012 + (m.status==='maintenance'?.35:rnd(-.08,.04))),8,99);
    if(m.health<28 || m.temperature>92 || m.vibration>7.7) m.status='critical';
    m.failure=clamp(100-m.health+m.vibration*2+rnd(-2,2),1,98);
    m.history.push(m.temperature); if(m.history.length>28)m.history.shift();
  });
  const running=d.machines.filter(m=>m.status==='running');
  const inc=Math.round(running.reduce((a,m)=>a+m.utilization/100,0)*rnd(1.4,2.6));
  d.production+=inc; d.target=15000;
  d.defects+=Math.random()<.45?Math.round(rnd(0,3)):0;
  d.productionHistory.push((d.productionHistory.at(-1)||1000)+Math.round(rnd(-90,160))); if(d.productionHistory.length>24)d.productionHistory.shift();
  d.energyHistory.push(Math.round(d.machines.reduce((a,m)=>a+m.power,0)*rnd(2.4,3.5))); if(d.energyHistory.length>24)d.energyHistory.shift();
  d.qualityHistory.push(clamp(100-d.defects/Math.max(1,d.production)*100+rnd(-.2,.22),90,99.9)); if(d.qualityHistory.length>24)d.qualityHistory.shift();
  d.inventory.forEach((it,i)=>{ if(i<3) it.current=clamp(it.current-rnd(.05,1.8),0,99999); });
  d.carbon += d.machines.reduce((a,m)=>a+m.power,0)*.00012; d.revenue += inc*19;
  const hot=d.machines.find(m=>m.temperature>state.settings.alertTemp && Math.random()<.08);
  if(hot) d.alerts.unshift(makeAlert(hot.id, `${hot.name} overheating at ${hot.temperature.toFixed(1)}°C`, hot.status));
  const low=d.inventory.find(i=>i.current<i.min && Math.random()<.04);
  if(low) d.alerts.unshift(makeAlert('Inventory Low', `${low.name} is below minimum stock`, 'maintenance'));
  d.alerts=d.alerts.slice(0,12);
}
setInterval(()=>{tick(); if(state.authed && !isTyping()) render();},2600);
function isTyping(){const a=document.activeElement;return a && ['INPUT','TEXTAREA','SELECT'].includes(a.tagName);}

function metrics(){
  const d=state.data, machines=d.machines, total=machines.length;
  const count=s=>machines.filter(m=>m.status===s).length;
  const avg=arr=>arr.reduce((a,b)=>a+b,0)/Math.max(1,arr.length);
  const running=count('running'), idle=count('idle'), maintenance=count('maintenance'), offline=count('offline'), critical=count('critical');
  const energy=machines.reduce((a,m)=>a+m.power,0)*8.3;
  const quality=clamp(100-d.defects/Math.max(1,d.production)*100,80,99.8);
  const machineHealth=avg(machines.map(m=>m.health));
  const prodScore=clamp(d.production/d.target*100,0,100);
  const energyScore=clamp(100-energy/20,40,100), invScore=clamp(avg(d.inventory.map(i=>clamp(i.current/i.min*70,0,100))),0,100);
  const health=clamp(Math.round(machineHealth*.28+prodScore*.22+energyScore*.15+quality*.18+92*.08+invScore*.09),0,100);
  return {total,running,idle,maintenance,offline,critical,energy,quality,machineHealth,health,workersPresent:state.data.workers.filter(w=>w.status!=='Absent').length, cost:energy*state.settings.rate, downtime:machines.reduce((a,m)=>a+m.downtime,0), oee:clamp((prodScore*.4+quality*.3+machineHealth*.3),0,99), activeAlerts:d.alerts.filter(a=>!a.read).length};
}

function spark(values,color='var(--brand2)',h=78){
  const w=220, min=Math.min(...values), max=Math.max(...values), span=max-min||1;
  const pts=values.map((v,i)=>`${i/(values.length-1)*w},${h-8-((v-min)/span)*(h-18)}`).join(' ');
  const area=`0,${h} ${pts} ${w},${h}`;
  return `<svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="g${Math.round(Math.random()*9999)}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${color}" stop-opacity=".42"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><polygon points="${area}" fill="rgba(74,164,255,.18)"/><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round"/></svg>`;
}
function bars(values,color='var(--brand)'){const max=Math.max(...values);return `<div style="height:100%;display:flex;gap:10px;align-items:end">${values.map(v=>`<div title="${Math.round(v)}" style="height:${v/max*92+6}%;flex:1;border-radius:10px 10px 3px 3px;background:linear-gradient(180deg,${color},rgba(59,214,255,.25));box-shadow:0 0 18px rgba(101,87,255,.25)"></div>`).join('')}</div>`;}
function kpi(title,val,sub,trend='good',progress=80){return `<div class="card kpi"><div class="kpi-top"><span>${title}</span><span class="${trend}">${sub||''}</span></div><div><div class="kpi-val mono">${val}</div><div class="progress"><span style="width:${clamp(progress,0,100)}%"></span></div></div></div>`;}
function statusChip(s){return `<span class="status ${s}"><span class="dot ${s}"></span>${statusLabel[s]}</span>`;}

function render(){
  app.innerHTML = `<div class="app-bg"><div class="noise"></div><div class="orb one"></div><div class="orb two"></div><div class="orb three"></div>${state.authed?renderShell():renderPublic()}${state.toast?`<div class="toast">${state.toast}</div>`:''}</div>`;
  if(state.toast) setTimeout(()=>{state.toast='';render();},1800);
}
function renderPublic(){
  return `<main class="public"><nav class="public-nav"><div class="logo"><span class="logo-mark"></span><span>FactoryOS</span></div><div class="toolbar"><button class="btn ghost" data-action="auth-mode" data-mode="login">Login</button><button class="btn primary" data-action="auth-mode" data-mode="register">Start Prototype</button></div></nav>
  <section class="hero"><div><span class="chip"><span class="dot running"></span>AI-powered factory command center</span><h1>Smart Manufacturing OS for modern MSMEs.</h1><p>Monitor every machine, forecast maintenance, control energy cost, inspect quality, manage inventory, and generate executive reports from one premium operating system.</p><div class="toolbar"><button class="btn primary" data-action="auth-mode" data-mode="login">Enter FactoryOS</button><button class="btn" data-action="auth-mode" data-mode="register">Create account</button></div>${authCard()}</div><div class="hero-panel glass"><div class="hero-grid"><div class="hero-kpi"><span class="tiny">Factory Health</span><strong>87</strong><span class="good">Excellent</span></div><div class="hero-kpi"><span class="tiny">Production</span><strong>12,842</strong><span class="good">85% target</span></div><div class="hero-kpi"><span class="tiny">Energy</span><strong>1,256</strong><span class="muted">kWh today</span></div><div class="hero-kpi"><span class="tiny">Alerts</span><strong>4</strong><span class="warn">Action needed</span></div></div><div class="hero-machine"><i class="hm a"></i><i class="hm b"></i><i class="hm c"></i></div></div></section></main>`;
}
function authCard(){
  const mode=state.authMode;
  const title=mode==='login'?'Secure Login':mode==='register'?'Create FactoryOS Account':'Recover Password';
  return `<div class="auth-card glass"><div class="auth-tabs"><button class="btn ${mode==='login'?'primary':''}" data-action="auth-mode" data-mode="login">Login</button><button class="btn ${mode==='register'?'primary':''}" data-action="auth-mode" data-mode="register">Register</button><button class="btn ${mode==='forgot'?'primary':''}" data-action="auth-mode" data-mode="forgot">Forgot</button></div><h2>${title}</h2><p class="tiny">MFA-ready and role-based. Any demo credentials work.</p>${mode==='register'?`<label class="field"><span>Name</span><input id="name" value="Alex Johnson"></label>`:''}<label class="field"><span>Email</span><input id="email" value="owner@factoryos.ai"></label>${mode!=='forgot'?`<label class="field"><span>Password</span><input id="password" type="password" value="factoryos"></label><label class="field"><span>Role</span><select id="authRole">${Object.keys(ROLE_ACCESS).map(r=>`<option ${r===state.role?'selected':''}>${r}</option>`).join('')}</select></label>`:''}<button class="btn primary" style="width:100%;justify-content:center" data-action="${mode==='forgot'?'reset-password':'login'}">${mode==='forgot'?'Send reset link':'Continue to FactoryOS'}</button></div>`;
}
function renderShell(){
  const allowed=ROLE_ACCESS[state.role]||ROLE_ACCESS['Factory Owner']; if(!allowed.includes(state.route)) state.route='dashboard';
  return `<div class="shell ${state.sidebar?'open':''}"><aside class="sidebar"><div class="logo"><span class="logo-mark"></span><span>FactoryOS</span></div><div class="nav">${NAV.filter(n=>allowed.includes(n[0])).map(n=>`<button data-action="nav" data-route="${n[0]}" class="${state.route===n[0]?'active':''}"><span class="ico">${n[2]}</span><span>${n[1]}</span></button>`).join('')}</div><div class="sidebar-foot"><div class="user-pill"><span class="avatar">AJ</span><div><strong>Alex Johnson</strong><div class="tiny">${state.role}</div></div></div></div></aside><section class="main"><header class="topbar"><div class="top-left"><button class="btn mobile-menu" data-action="mobile-menu">Menu</button><div><strong class="mono"><span class="dot running"></span> Live</strong><div class="tiny">Last updated: ${nowTime()}</div></div></div><div class="toolbar"><div class="search-wrap"><input class="searchbox" id="globalSearch" placeholder="Search machines, employees, reports, alerts..." value="${state.search}">${state.search?searchResults():''}</div><select class="searchbox" id="roleSelect" style="max-width:210px">${Object.keys(ROLE_ACCESS).map(r=>`<option ${r===state.role?'selected':''}>${r}</option>`).join('')}</select><button class="btn" data-action="theme">${state.theme==='dark'?'Light':'Dark'}</button><button class="btn" data-action="logout">Logout</button></div></header><main class="page">${renderPage()}</main></section></div>`;
}
function searchResults(){
  const q=state.search.toLowerCase();
  const items=[]; state.data.machines.forEach(m=>items.push({type:'Machine',name:`${m.id} ${m.name}`,meta:m.section,route:'machines'}));
  state.data.workers.forEach(w=>items.push({type:'Employee',name:w.name,meta:w.role,route:'workers'})); state.data.inventory.forEach(i=>items.push({type:'Inventory',name:i.name,meta:i.category,route:'inventory'}));
  state.data.alerts.forEach(a=>items.push({type:'Alert',name:a.title,meta:a.msg,route:'alerts'})); ['Daily Report','Energy Report','Maintenance Report','Quality Report','Inventory Report'].forEach(r=>items.push({type:'Report',name:r,meta:'Generated report',route:'reports'}));
  return `<div class="search-results glass">${items.filter(i=>(i.name+i.meta+i.type).toLowerCase().includes(q)).slice(0,7).map(i=>`<div class="result" data-action="nav" data-route="${i.route}"><div><strong>${i.name}</strong><div class="tiny">${i.type} · ${i.meta}</div></div><span class="chip">Open</span></div>`).join('')||'<div class="tiny">No results found</div>'}</div>`;
}
function renderPage(){return ({dashboard:dashboardPage,copilot:copilotPage,digital:digitalTwinPage,machines:machinesPage,maintenance:maintenancePage,production:productionPage,vision:visionPage,quality:qualityPage,workers:workersPage,energy:energyPage,sustainability:sustainabilityPage,inventory:inventoryPage,alerts:alertsPage,analytics:analyticsPage,reports:reportsPage,loss:lossPage,health:healthPage,users:usersPage,settings:settingsPage}[state.route]||dashboardPage)();}
function header(title,sub,actions=''){return `<div class="section-title"><div><h1>${title}</h1><p>${sub}</p></div><div class="toolbar">${actions}</div></div>`;}
function dashboardPage(){const m=metrics(),d=state.data;return `${header('Factory Overview','Real-time overview of your factory operations.',`<button class="btn" data-action="export-csv" data-kind="dashboard">Export CSV</button><button class="btn primary" data-action="nav" data-route="copilot">Ask AI</button>`)}<div class="grid kpis">${kpi('Factory Health Score',`${m.health}<small>/100</small>`,'Excellent','good',m.health)}${kpi('Today Production',fmt(d.production),'Target '+fmt(d.target),'good',d.production/d.target*100)}${kpi('Active Machines',`${m.running}<small>/${m.total}</small>`,'Running','good',m.running/m.total*100)}${kpi('Energy Consumption',`${Math.round(m.energy).toLocaleString()} kWh`,'Cost ₹'+fmt(Math.round(m.cost)),'good',72)}${kpi('Defective Products',fmt(d.defects),`${(100-m.quality).toFixed(2)}% of total`,'bad',100-m.quality)}${kpi('Workers Present',`${m.workersPresent}<small>/${d.workers.length}</small>`,'On Floor','good',m.workersPresent/d.workers.length*100)}</div><div class="grid two" style="margin-top:16px"><div class="card"><div class="panel-header"><div><h3>Production Trend</h3><span class="tiny">Today</span></div><span class="chip">This Hour</span></div><div class="chart-wrap">${spark(d.productionHistory,'#6557ff',230)}</div></div><div class="card"><div class="panel-header"><h3>Machine Status</h3><span class="chip">${m.total} Total</span></div><div style="display:flex;align-items:center;gap:26px;justify-content:center"><div class="donut" data-label="${m.total}\A Total" style="white-space:pre"></div><div style="min-width:220px">${['running','idle','maintenance','offline','critical'].map(s=>`<div class="metric-line"><b>${statusLabel[s]}</b><div class="bar"><i style="width:${(m[s]/m.total*100)}%"></i></div><span>${m[s]}</span></div>`).join('')}</div></div></div></div><div class="grid two" style="margin-top:16px"><div class="card"><div class="panel-header"><h3>Customizable Widgets</h3><span class="tiny">Drag cards to reorder</span></div><div class="grid auto">${state.widgets.map(widgetCard).join('')}</div></div><div class="card"><div class="panel-header"><h3>Active Alerts</h3><button class="btn ghost" data-action="nav" data-route="alerts">View all</button></div><div class="list">${d.alerts.slice(0,6).map(alertRow).join('')}</div></div></div>`;}
function widgetCard(w){const m=metrics(),d=state.data;const map={production:[fmt(d.production),'Units produced','good',d.production/d.target*100],health:[m.health+'/100','Factory health','good',m.health],energy:[Math.round(m.energy)+' kWh','Today usage','good',74],alerts:[m.activeAlerts,'Unresolved alerts',m.activeAlerts?'warn':'good',60],quality:[m.quality.toFixed(2)+'%','Quality rate','good',m.quality],inventory:[d.inventory.filter(i=>i.current<i.min).length,'Low stock items','warn',65],revenue:['₹ '+(d.revenue/100000).toFixed(2)+'L','Revenue estimate','good',79],carbon:[Math.round(d.carbon)+' kg','Carbon footprint','good',55],shift:['Shift A','96 active operators','good',92],weather:['29°C','Plant ambient','good',70]};let v=map[w]||map.production;return `<div class="card compact" draggable="true" data-widget="${w}"><div class="kpi-top"><span>${w[0].toUpperCase()+w.slice(1)}</span><span class="${v[2]}">${v[1]}</span></div><div class="kpi-val mono">${v[0]}</div><div class="progress"><span style="width:${v[3]}%"></span></div></div>`;}
function alertRow(a){return `<div class="row"><div><strong><span class="dot ${a.severity}"></span> ${a.title}</strong><div class="tiny">${a.msg}</div></div><span class="tiny">${a.time}</span></div>`;}

function digitalTwinPage(){const d=state.data,m=metrics(),sel=d.machines.find(x=>x.id===state.selectedMachine)||d.machines[3];return `${header('Factory Digital Twin','Interactive 3D-like live representation of your factory.',`<span class="chip"><span class="dot running"></span>${m.running} Running</span><span class="chip"><span class="dot critical"></span>${m.critical} Critical</span>`)}<div class="factory-area"><div class="factory-stage glass"><div class="toolbar" style="position:absolute;z-index:4;left:22px;top:18px">${['running','idle','maintenance','offline','critical'].map(s=>`<span class="chip"><span class="dot ${s}"></span>${statusLabel[s]}</span>`).join('')}</div><div class="factory-floor"><div class="zone" style="left:6%;top:8%;width:28%;height:28%">CNC Area</div><div class="zone" style="left:38%;top:8%;width:26%;height:29%">Assembly</div><div class="zone" style="left:67%;top:10%;width:25%;height:32%">Packaging</div><div class="zone" style="left:7%;top:50%;width:28%;height:35%">Warehouse</div><div class="zone" style="left:39%;top:52%;width:25%;height:32%">Quality</div><div class="zone" style="left:67%;top:55%;width:25%;height:30%">Utilities</div></div>${d.machines.slice(0,14).map(machineNode).join('')}<div class="toolbar" style="position:absolute;left:50%;bottom:20px;transform:translateX(-50%);z-index:5"><button class="btn primary">Pointer</button><button class="btn">Pan</button><button class="btn">Zoom</button><button class="btn">Full</button></div></div><div class="machine-side card">${machineDetails(sel)}</div></div>`;}
function machineNode(m){const x=m.x,y=m.y;return `<button class="machine-node ${m.status}" data-action="select-machine" data-id="${m.id}" style="left:${x}%;top:${y}%;" title="${m.name}"></button><button class="machine-tag" data-action="select-machine" data-id="${m.id}" style="left:${x+1}%;top:${y-4}%"><strong>${m.id}</strong><span class="dot ${m.status}"></span> ${statusLabel[m.status]}</button>`;}
function machineDetails(m){return `<div class="panel-header"><div><h2>${m.name}</h2><span class="tiny">${m.id} · ${m.section}</span></div>${statusChip(m.status)}</div><div class="tabs"><button class="active">Overview</button><button>Health</button><button>Maintenance</button><button>History</button></div><div class="telemetry" style="margin-top:16px">${[['Temperature',m.temperature.toFixed(1)+'°C','bad'],['Vibration',m.vibration.toFixed(1)+' mm/s','bad'],['Power',m.power.toFixed(1)+' kW','good'],['Health Score',Math.round(m.health)+'/100',m.health<50?'bad':'good'],['Runtime',m.runtime.toFixed(1)+'h',''],['Output',fmt(m.output)+' units','good']].map(([a,b,c])=>`<div class="mini"><span class="tiny">${a}</span><h3 class="${c} mono">${b}</h3>${spark(m.history.slice(-12),c==='bad'?'#ff525f':'#31e086',46)}</div>`).join('')}</div><h3 style="margin-top:18px">Maintenance History</h3><div class="list">${m.maint.map(x=>`<div class="row"><span>${x}</span><span class="chip">Logged</span></div>`).join('')}</div><button class="btn primary" style="width:100%;justify-content:center;margin-top:16px" data-action="nav" data-route="maintenance">View Full Details</button>`;}

function machinesPage(){const rows=state.data.machines.filter(m=>state.machineFilter==='all'||m.status===state.machineFilter);return `${header('Machines','Monitor all machines in real-time.',`<select class="searchbox" id="machineFilter" style="max-width:180px"><option value="all">All Status</option>${Object.keys(statusLabel).map(s=>`<option value="${s}" ${state.machineFilter===s?'selected':''}>${statusLabel[s]}</option>`).join('')}</select><button class="btn primary" data-action="add-machine">Add Machine</button>`)}<div class="table-wrap"><table class="table"><thead><tr><th>Machine ID</th><th>Machine Name</th><th>Status</th><th>Temperature</th><th>Vibration</th><th>RPM</th><th>Power</th><th>Runtime</th><th>Utilization</th><th>Health Score</th></tr></thead><tbody>${rows.map(m=>`<tr data-action="select-machine" data-id="${m.id}"><td>${m.id}</td><td>${m.name}</td><td>${statusChip(m.status)}</td><td class="${m.temperature>85?'bad':''}">${m.temperature.toFixed(1)}°C</td><td>${m.vibration.toFixed(1)} mm/s</td><td>${m.rpm}</td><td>${m.power.toFixed(1)} kW</td><td>${m.runtime.toFixed(1)}h</td><td>${Math.round(m.utilization)}%</td><td class="${m.health<50?'bad':'good'}">${Math.round(m.health)}/100</td></tr>`).join('')}</tbody></table></div>`;}

function maintenancePage(){const machines=[...state.data.machines].sort((a,b)=>b.failure-a.failure).slice(0,8);return `${header('Predictive Maintenance','Rule-based AI classifies health, failure probability, RUL, parts, and schedule.',`<button class="btn" data-action="export-csv" data-kind="maintenance">Export Logs</button><button class="btn primary" data-action="toast" data-msg="Maintenance calendar synchronized">Sync Calendar</button>`)}<div class="grid four">${kpi('Maintenance Due','12','This month','warn',70)}${kpi('In Progress','5','Open jobs','good',45)}${kpi('Completed','18','This month','good',88)}${kpi('Overdue','3','Critical priority','bad',28)}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>AI Maintenance Priority</h3><div class="list" style="margin-top:14px">${machines.map(m=>`<div class="row"><div><strong>${m.id} ${m.name}</strong><div class="tiny">${healthClass(m)} · RUL ${Math.max(1,Math.round(m.health/7))} days · Parts: ${partFor(m)}</div></div><div><b class="${m.failure>70?'bad':m.failure>45?'warn':'good'}">${Math.round(m.failure)}%</b><div class="tiny">failure probability</div></div></div>`).join('')}</div></div><div class="card"><h3>Maintenance Calendar</h3><div class="calendar" style="margin-top:14px">${Array.from({length:28},(_,i)=>`<div class="day ${[4,9,16,23].includes(i)?'event':''}"><b>${i+1}</b><span class="tiny">${[4,9,16,23].includes(i)?'Service M-'+String(i+1).padStart(2,'0'):'Available'}</span></div>`).join('')}</div></div></div>`;}
function healthClass(m){return m.status==='critical'||m.health<35?'Critical':m.health<55?'Maintenance Required':m.health<75?'Warning':'Healthy';}
function partFor(m){return m.vibration>6?'Bearings':m.temperature>84?'Coolant pump':m.runtime>10?'Lubricant kit':'Inspection kit';}
function productionPage(){const d=state.data,m=metrics();return `${header('Production Management','Live production planning, OEE, shift performance, forecast, and losses.',`<button class="btn" data-action="export-csv" data-kind="production">Export Production</button><button class="btn primary" data-action="toast" data-msg="Production forecast recalculated">Forecast</button>`)}<div class="grid four">${kpi('Today Production',fmt(d.production),'Units','good',d.production/d.target*100)}${kpi('Production Target',fmt(d.target),'Daily goal','good',100)}${kpi('OEE',m.oee.toFixed(1)+'%','Good','good',m.oee)}${kpi('Production Loss',fmt(Math.round((d.target-d.production)*19)),'Estimated ₹','bad',42)}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Hourly Production</h3><div class="chart-wrap">${bars(d.productionHistory,'#6557ff')}</div></div><div class="card"><h3>Production by Line</h3><div style="display:flex;gap:28px;align-items:center;justify-content:center;height:260px"><div class="donut" data-label="${fmt(d.production)}\A Units" style="white-space:pre"></div><div>${['Line 1','Line 2','Line 3','Line 4'].map((l,i)=>`<div class="metric-line"><b>${l}</b><div class="bar"><i style="width:${[35,28,21,16][i]}%"></i></div><span>${[35,28,21,16][i]}%</span></div>`).join('')}</div></div></div></div><div class="card" style="margin-top:16px"><h3>Top Performing Machines</h3><div class="table-wrap" style="margin-top:14px"><table class="table"><tbody>${[...d.machines].sort((a,b)=>b.output-a.output).slice(0,7).map(m=>`<tr><td>${m.id}</td><td>${m.name}</td><td>${fmt(m.output)} units</td><td>${Math.round(m.utilization)}% efficiency</td><td class="good">On track</td></tr>`).join('')}</tbody></table></div></div>`;}
function visionPage(){return `${header('AI Vision','Simulated computer vision for count, defects, PPE, fire, smoke, and restricted zones.',`<button class="btn primary" data-action="toast" data-msg="Camera adapter ready for future webcam integration">Connect Camera</button>`)}<div class="grid four">${kpi('Product Count',fmt(state.data.production),'Detected','good',88)}${kpi('Defective Count',fmt(state.data.defects),'Vision defects','bad',18)}${kpi('PPE Compliance','96%','Helmet + vest','good',96)}${kpi('Safety Events','2','Today','warn',35)}</div><div class="grid two" style="margin-top:16px"><div class="card"><div class="vision-feed"><div class="box-detect" style="left:12%;top:18%;width:22%;height:28%">Helmet OK</div><div class="box-detect warn" style="left:55%;top:14%;width:18%;height:20%">Vest Missing</div><div class="box-detect" style="left:35%;top:62%;width:22%;height:18%">Product Count</div><div class="box-detect bad" style="left:72%;top:55%;width:16%;height:21%">Smoke Risk</div></div></div><div class="card"><h3>Vision Detections</h3><div class="list" style="margin-top:14px">${['Helmet Detection 98%','Safety Vest Detection 94%','Smoke Detection 1 event','Fire Detection 0 events','Restricted Zone 1 breach','Product Count Confidence 97%'].map((x,i)=>`<div class="row"><span>${x}</span><span class="chip ${i>1?'warn':''}">${i<2?'Safe':'Watch'}</span></div>`).join('')}</div></div></div>`;}
function qualityPage(){const d=state.data,m=metrics();return `${header('Quality Control','Track inspection quality, batch history, defects, and AI quality score.',`<button class="btn" data-action="export-csv" data-kind="quality">Export Quality</button>`)}<div class="grid four">${kpi('Good Products',fmt(d.production-d.defects),'Passed','good',m.quality)}${kpi('Defective Products',fmt(d.defects),'Today','bad',100-m.quality)}${kpi('Defect Rate',(100-m.quality).toFixed(2)+'%','Good','good',100-m.quality)}${kpi('AI Quality Score',Math.round(m.quality-1)+'/100','Excellent','good',m.quality)}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Defect Trend</h3><div class="chart-wrap">${spark(state.data.qualityHistory.map(v=>100-v),'#ff525f',230)}</div></div><div class="card"><h3>Defect by Type</h3><div style="display:flex;align-items:center;gap:24px;justify-content:center"><div class="donut" data-label="${d.defects}\A Defects" style="white-space:pre"></div><div>${['Scratch','Dent','Misalign','Surface','Weight','Crack'].map((x,i)=>`<div class="metric-line"><b>${x}</b><div class="bar"><i style="width:${[28,22,18,14,10,8][i]}%"></i></div><span>${[28,22,18,14,10,8][i]}%</span></div>`).join('')}</div></div></div></div><div class="card" style="margin-top:16px"><h3>Recent Batches</h3><div class="table-wrap" style="margin-top:14px"><table class="table"><tbody>${Array.from({length:6},(_,i)=>`<tr><td>B-${2401+i}</td><td>Line ${i%4+1}</td><td>${fmt(980+i*73)} units</td><td>${(rnd(1,3)).toFixed(2)}% defects</td><td class="good">Released</td></tr>`).join('')}</tbody></table></div></div>`;}
function workersPage(){const w=state.data.workers,m=metrics();return `${header('Worker Management','Attendance, shift allocation, productivity, operators, and safety compliance.',`<button class="btn primary" data-action="toast" data-msg="Attendance report generated">View Attendance</button>`)}<div class="grid four">${kpi('Total Workers',w.length,'Registered','good',100)}${kpi('Present Today',m.workersPresent,'On site','good',m.workersPresent/w.length*100)}${kpi('On Leave','12','Factory wide','warn',42)}${kpi('On Shift','96','Active operators','good',88)}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Workers by Shift</h3><div style="display:flex;align-items:center;gap:26px;justify-content:center;height:250px"><div class="donut" data-label="128\A Present" style="white-space:pre"></div><div>${['Morning','Evening','Night'].map((x,i)=>`<div class="metric-line"><b>${x}</b><div class="bar"><i style="width:${[48,32,20][i]}%"></i></div><span>${[48,32,20][i]}%</span></div>`).join('')}</div></div></div><div class="card"><h3>Recent Attendance</h3><div class="list" style="margin-top:14px">${w.slice(0,7).map(x=>`<div class="row"><div><strong>${x.name}</strong><div class="tiny">${x.role} · Shift ${x.shift}</div></div><span class="chip"><span class="dot running"></span>${x.status}</span></div>`).join('')}</div></div></div>`;}
function energyPage(){const d=state.data,m=metrics();return `${header('Energy Management','Monitor and optimize energy consumption, cost, peak demand, and efficiency.',`<button class="btn" data-action="export-csv" data-kind="energy">Export Energy</button><button class="btn primary" data-action="toast" data-msg="AI energy suggestions refreshed">AI Suggestions</button>`)}<div class="grid four">${kpi('Total Energy',Math.round(m.energy)+' kWh','Today','good',78)}${kpi('Total Cost','₹ '+fmt(Math.round(m.cost)),'Today','good',68)}${kpi('Peak Demand','198 kW','05:30 PM','warn',76)}${kpi('Energy Efficiency','76%','Good','good',76)}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Energy Consumption</h3><div class="chart-wrap">${spark(d.energyHistory,'#49a4ff',230)}</div></div><div class="card"><h3>Energy by Machine</h3><div class="list">${[...d.machines].sort((a,b)=>b.power-a.power).slice(0,7).map(m=>`<div class="metric-line"><b>${m.id}</b><div class="bar"><i style="width:${m.power/26*100}%"></i></div><span>${m.power.toFixed(1)} kW</span></div>`).join('')}</div></div></div><div class="card" style="margin-top:16px;background:linear-gradient(135deg,rgba(101,87,255,.24),rgba(59,214,255,.08))"><h3>AI Energy Suggestions</h3><div class="list" style="margin-top:12px"><div class="row">Reduce runtime of Machine 04 during peak hours.</div><div class="row">Shift high-load Line 2 to 11 PM for lower electricity costs.</div><div class="row">Compressor leakage check can save 44 kWh today.</div></div></div>`;}
function sustainabilityPage(){const d=state.data,m=metrics();return `${header('Sustainability Dashboard','Carbon, water, energy saving, waste, ESG reporting, and sustainability score.',`<button class="btn primary" data-action="toast" data-msg="Monthly ESG report generated">Generate ESG Report</button>`)}<div class="grid four">${kpi('Carbon Emission',Math.round(d.carbon)+' kg CO₂','Today','good',62)}${kpi('Water Usage','18.4 KL','Today','good',54)}${kpi('Energy Saving','12.8%','Month','good',74)}${kpi('Sustainability Score','82/100','Strong','good',82)}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Carbon Trend</h3><div class="chart-wrap">${spark(d.energyHistory.map(x=>x*.54),'#31e086',230)}</div></div><div class="card"><h3>Waste Generation</h3><div class="list">${['Metal scrap 128 kg','Packaging waste 42 kg','Oil waste 16 L','Reusable material 74%'].map((x,i)=>`<div class="row"><span>${x}</span><span class="chip ${i<2?'warn':'good'}">${i<2?'Reduce':'Good'}</span></div>`).join('')}</div></div></div>`;}
function inventoryPage(){const inv=state.data.inventory;return `${header('Inventory Management','Raw materials, finished goods, suppliers, purchase suggestions, and AI forecast.',`<button class="btn" data-action="export-csv" data-kind="inventory">Export Inventory</button><button class="btn primary" data-action="reorder-inventory">Auto Reorder</button>`)}<div class="grid four">${kpi('Raw Materials','156','Items','good',82)}${kpi('Low Stock',inv.filter(i=>i.current<i.min).length,'Needs reorder','warn',38)}${kpi('Out of Stock','3','Critical','bad',20)}${kpi('Total Value','₹12.45L','Inventory','good',78)}</div><div class="card" style="margin-top:16px"><h3>Stock and Suppliers</h3><div class="table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>Item</th><th>Category</th><th>Current Stock</th><th>Min Stock</th><th>Supplier</th><th>Status</th></tr></thead><tbody>${inv.map(i=>`<tr><td>${i.name}</td><td>${i.category}</td><td>${Math.round(i.current)} ${i.unit}</td><td>${i.min} ${i.unit}</td><td>${i.supplier}</td><td><span class="chip ${i.current<i.min?'bad':'good'}">${i.current<i.min?'Low':'OK'}</span></td></tr>`).join('')}</tbody></table></div></div><div class="card" style="margin-top:16px"><h3>AI Inventory Forecast</h3><div class="list">${inv.slice(0,5).map(i=>`<div class="row"><span>${i.name}</span><span>${i.current<i.min?'Reorder now':'Sufficient for '+Math.round(i.current/Math.max(1,i.min)*7)+' days'}</span></div>`).join('')}</div></div>`;}
function alertsPage(){return `${header('Alerts Center','Real-time alerts, notifications, severity, and action history.',`<button class="btn primary" data-action="mark-alerts">Mark All Read</button>`)}<div class="grid four">${kpi('Active Alerts',metrics().activeAlerts,'Unresolved','warn',62)}${kpi('Critical',state.data.alerts.filter(a=>a.severity==='critical').length,'Immediate','bad',35)}${kpi('Notifications','Email / SMS / Push','Ready','good',88)}${kpi('Audit Events','126','Today','good',75)}</div><div class="card" style="margin-top:16px"><div class="list">${state.data.alerts.map(a=>`<div class="row"><div><strong><span class="dot ${a.severity}"></span> ${a.title}</strong><div class="tiny">${a.msg} · ${a.time}</div></div><div class="toolbar"><button class="btn">Acknowledge</button><button class="btn primary" data-action="nav" data-route="${a.title.includes('Inventory')?'inventory':'machines'}">Resolve</button></div></div>`).join('')}</div></div>`;}
function analyticsPage(){const d=state.data;return `${header('Analytics','Interactive production, machine health, energy, downtime, inventory, quality, revenue, and carbon trends.',`<button class="btn" data-action="export-html" data-kind="analytics">Export Analytics</button>`)}<div class="grid two"><div class="card"><h3>Production Trend</h3><div class="chart-wrap">${spark(d.productionHistory,'#6557ff',230)}</div></div><div class="card"><h3>Energy Trend</h3><div class="chart-wrap">${spark(d.energyHistory,'#49a4ff',230)}</div></div><div class="card"><h3>Quality Trend</h3><div class="chart-wrap">${spark(d.qualityHistory,'#31e086',230)}</div></div><div class="card"><h3>Revenue Trend</h3><div class="chart-wrap">${spark(d.productionHistory.map(x=>x*19),'#f2c84b',230)}</div></div><div class="card"><h3>Downtime Trend</h3><div class="chart-wrap">${bars(Array.from({length:16},()=>rnd(20,130)),'#ff525f')}</div></div><div class="card"><h3>Inventory Trend</h3><div class="chart-wrap">${bars(d.inventory.map(i=>i.current),'#31e086')}</div></div></div>`;}
function reportsPage(){const types=['Daily Report','Weekly Report','Monthly Report','Maintenance Report','Energy Report','Quality Report','Inventory Report','Executive Summary'];return `${header('Reports','Generate and download factory reports, snapshots, and executive summaries.',`<select class="searchbox" id="reportType" style="max-width:230px">${types.map(t=>`<option ${state.reportType===t?'selected':''}>${t}</option>`).join('')}</select><button class="btn primary" data-action="generate-report">Generate</button><button class="btn" data-action="export-html" data-kind="report">Export HTML</button><button class="btn" data-action="print">Print / PDF</button>`)}<div class="grid two"><div class="card"><h3>Report Library</h3><div class="list" style="margin-top:14px">${types.map(t=>`<div class="row"><div><strong>${t}</strong><div class="tiny">Updated ${nowTime()}</div></div><button class="btn" data-action="set-report" data-report="${t}">Select</button></div>`).join('')}</div></div><div class="card" style="background:#f8fbff;color:#101b2b"><div style="display:flex;justify-content:space-between;align-items:center"><h2>FactoryOS ${state.reportType}</h2><strong>FactoryOS</strong></div>${reportPreview()}</div></div>`;}
function reportPreview(){const m=metrics(),d=state.data;return `<div class="grid two" style="margin-top:18px"><div class="card" style="background:#fff;color:#111"><span class="tiny">Production</span><h2>${fmt(d.production)}</h2><div class="progress"><span style="width:${d.production/d.target*100}%"></span></div></div><div class="card" style="background:#fff;color:#111"><span class="tiny">OEE</span><h2>${m.oee.toFixed(1)}%</h2></div><div class="card" style="background:#fff;color:#111"><span class="tiny">Downtime</span><h2>${m.downtime.toFixed(1)}h</h2></div><div class="card" style="background:#fff;color:#111"><span class="tiny">Defect Rate</span><h2>${(100-m.quality).toFixed(2)}%</h2></div></div><div style="height:180px;margin-top:16px">${spark(d.productionHistory,'#6557ff',170)}</div>`;}
function lossPage(){const l=state.data.costLoss,total=Object.values(l).reduce((a,b)=>a+b,0);return `${header('Cost Loss Analyzer','Estimate production loss, downtime cost, energy waste, defects, maintenance, and revenue loss.',`<button class="btn primary" data-action="toast" data-msg="Loss model recalculated">Recalculate</button>`)}<div class="grid kpis">${kpi('Total Estimated Loss','₹ '+fmt(total),'Today','bad',72)}${kpi('Production Loss','₹ '+fmt(l.production),'Units gap','bad',68)}${kpi('Downtime Cost','₹ '+fmt(l.downtime),'Idle time','bad',56)}${kpi('Energy Waste','₹ '+fmt(l.energy),'Peak usage','warn',42)}${kpi('Defect Loss','₹ '+fmt(l.defects),'Quality','bad',38)}${kpi('Maintenance Cost','₹ '+fmt(l.maintenance),'Service','warn',45)}</div><div class="card" style="margin-top:16px"><h3>Recommended Loss Reduction Actions</h3><div class="list">${['Reduce Machine 04 load immediately.','Reorder Bearing 6205 to prevent line stoppage.','Move high power machines outside peak tariff.','Reduce idle time by 15% through shift balancing.','Train Operator 5 on defect-prone batch setup.'].map(x=>`<div class="row"><span>${x}</span><button class="btn">Create Task</button></div>`).join('')}</div></div>`;}
function healthPage(){const m=metrics();return `${header('Factory Health Score','Overall score from machine health, production, energy, quality, safety, and inventory.',`<button class="btn primary" data-action="toast" data-msg="Factory health score refreshed">Refresh Score</button>`)}<div class="grid two"><div class="card"><div class="health-ring" style="--score:${m.health}%"><div class="inside"><strong>${m.health}</strong><div class="tiny">/100 Excellent</div></div></div></div><div class="card"><h3>Score Components</h3>${[['Machine Health',m.machineHealth],['Production',state.data.production/state.data.target*100],['Energy',76],['Quality',m.quality],['Safety',92],['Inventory',81]].map(([a,b])=>`<div class="metric-line"><b>${a}</b><div class="bar"><i style="width:${b}%"></i></div><span>${Math.round(b)}%</span></div>`).join('')}<h3>AI Recommendations</h3><div class="list">${recommendations().map(x=>`<div class="row">${x}</div>`).join('')}</div></div></div>`;}
function usersPage(){return `${header('User Management','Factories, departments, production lines, machines, employees, suppliers, vendors, and permissions.',`<button class="btn primary" data-action="toast" data-msg="User invitation sent">Invite User</button>`)}<div class="grid three">${['Factory','Departments','Production Lines','Machines','Employees','Suppliers','Vendors','Permissions','Audit Logs'].map((x,i)=>`<div class="card"><div class="kpi-top"><span>${x}</span><span class="chip">Manage</span></div><div class="kpi-val">${[1,8,12,state.data.machines.length,state.data.workers.length,14,9,Object.keys(ROLE_ACCESS).length,126][i]}</div><button class="btn" data-action="toast" data-msg="${x} management panel opened">Open</button></div>`).join('')}</div><div class="card" style="margin-top:16px"><h3>Role Permissions</h3><div class="table-wrap" style="margin-top:14px"><table class="table"><tbody>${Object.entries(ROLE_ACCESS).map(([r,arr])=>`<tr><td>${r}</td><td>${arr.length} modules</td><td>${arr.slice(0,6).join(', ')}${arr.length>6?'...':''}</td><td><button class="btn">Edit</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function settingsPage(){const s=state.settings;return `${header('Factory Settings','Factory information, electricity rate, shifts, thresholds, AI configuration, theme, language, timezone.',`<button class="btn primary" data-action="save-settings">Save Settings</button>`)}<div class="grid two"><div class="card"><h3>Factory Information</h3>${[['factory','Factory Name'],['rate','Electricity Rate / kWh'],['shift','Working Hours'],['timezone','Timezone'],['language','Language'],['alertTemp','Temperature Alert °C'],['alertVibration','Vibration Alert mm/s']].map(([id,label])=>`<label class="field"><span>${label}</span><input data-setting="${id}" value="${s[id]}"></label>`).join('')}</div><div class="card"><h3>AI and IoT Configuration</h3><div class="list" style="margin-top:14px">${['Rule-based AI Engine enabled','OpenAI API ready','Ollama/local LLM ready','MQTT adapter ready','OPC-UA adapter ready','Modbus adapter ready','Camera/OpenCV adapter ready','Redis cache ready','PostgreSQL Prisma ready'].map(x=>`<div class="row"><span>${x}</span><span class="chip"><span class="dot running"></span>Ready</span></div>`).join('')}</div></div></div>`;}
function copilotPage(){return `${header('AI Factory Copilot','ChatGPT-style assistant with simulated structured backend and future LLM adapter.',`<button class="btn" data-action="generate-report">Generate Report</button>`)}<div class="chat"><div class="card"><h3>Suggested Questions</h3><div class="list" style="margin-top:14px">${['Why did production decrease today?','Which machine needs maintenance?','Show today\'s electricity cost.','Predict tomorrow\'s production.','Which machine consumes the most electricity?','Generate inventory report.','Summarize factory performance.'].map(q=>`<button class="btn" style="justify-content:flex-start" data-action="ask-suggestion" data-prompt="${q}">${q}</button>`).join('')}</div></div><div class="card chat-main"><div class="messages">${state.chat.map(c=>`<div class="msg ${c.who==='user'?'user':'ai'}">${c.text}</div>`).join('')}</div><div class="chat-input"><input class="searchbox" id="chatPrompt" placeholder="Ask anything about your factory..."><button class="btn primary" data-action="send-chat">Send</button></div></div><div class="card"><div class="bot"></div><h3>Today’s Summary</h3>${kpi('Production',fmt(state.data.production),'Units','good',82)}${kpi('Energy Cost','₹ '+fmt(Math.round(metrics().cost)),'Today','good',64)}${kpi('Defect Rate',(100-metrics().quality).toFixed(2)+'%','Needs focus','bad',32)}</div></div>`;}
function recommendations(){return ['Schedule maintenance for Machine 04.','Reduce Machine 02 load during peak tariff.','Reorder Steel Sheets and Bearing 6205.','Switch Line 3 to night shift for lower electricity cost.','Train Operator 5 on inspection checklist.','Reduce idle time by 15%.'];}
function aiAnswer(q){const lower=q.toLowerCase(),m=metrics(),d=state.data,hot=[...d.machines].sort((a,b)=>b.failure-a.failure)[0],energy=[...d.machines].sort((a,b)=>b.power-a.power)[0];
 if(lower.includes('maintenance')||lower.includes('which machine')) return `<strong>${hot.id} ${hot.name}</strong> needs maintenance first. Failure probability is <strong>${Math.round(hot.failure)}%</strong>, health is <strong>${Math.round(hot.health)}/100</strong>, vibration is <strong>${hot.vibration.toFixed(1)} mm/s</strong>. Recommendation: inspect ${partFor(hot)} and schedule service within ${Math.max(1,Math.round(hot.health/8))} days.`;
 if(lower.includes('electricity')||lower.includes('energy')||lower.includes('consumes')) return `Today's estimated energy use is <strong>${Math.round(m.energy)} kWh</strong> and electricity cost is <strong>₹${fmt(Math.round(m.cost))}</strong>. Highest consumer: <strong>${energy.id} ${energy.name}</strong> at ${energy.power.toFixed(1)} kW. Reduce runtime during peak hours and shift Line 2 load to night tariff.`;
 if(lower.includes('production')||lower.includes('decrease')||lower.includes('tomorrow')) return `Production is <strong>${fmt(d.production)}</strong> units against target <strong>${fmt(d.target)}</strong>. Primary constraints are critical Machine 04 downtime, low Bearing 6205 stock, and quality rework. Tomorrow forecast: <strong>${fmt(Math.round(d.production*1.06))}</strong> units if maintenance actions are completed.`;
 if(lower.includes('inventory')) return `Inventory risk detected: ${d.inventory.filter(i=>i.current<i.min).map(i=>`<strong>${i.name}</strong>`).join(', ') || 'no low stock items'}. AI suggestion: issue purchase order for 7-day safety stock and link consumption to production run rate.`;
 if(lower.includes('report')||lower.includes('summarize')) return `Executive summary: factory health <strong>${m.health}/100</strong>, OEE <strong>${m.oee.toFixed(1)}%</strong>, quality <strong>${m.quality.toFixed(2)}%</strong>, active alerts <strong>${m.activeAlerts}</strong>, energy cost <strong>₹${fmt(Math.round(m.cost))}</strong>. Suggested actions: ${recommendations().slice(0,3).join(' ')}`;
 return `FactoryOS analyzed live telemetry. Current health is <strong>${m.health}/100</strong>, ${m.running}/${m.total} machines are running, quality is <strong>${m.quality.toFixed(2)}%</strong>, and active alerts are <strong>${m.activeAlerts}</strong>. Top recommendation: ${recommendations()[0]}`;}
function download(name,content,type='text/csv'){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(a.href);}
function csvFor(kind){const d=state.data,m=metrics(); if(kind==='inventory') return 'Item,Category,Current,Minimum,Supplier\n'+d.inventory.map(i=>`${i.name},${i.category},${Math.round(i.current)} ${i.unit},${i.min} ${i.unit},${i.supplier}`).join('\n'); if(kind==='maintenance') return 'Machine,Health,Failure Probability,Status,Part\n'+d.machines.map(x=>`${x.id} ${x.name},${Math.round(x.health)},${Math.round(x.failure)}%,${x.status},${partFor(x)}`).join('\n'); if(kind==='energy') return 'Machine,Power kW,Status,Section\n'+d.machines.map(x=>`${x.id} ${x.name},${x.power.toFixed(1)},${x.status},${x.section}`).join('\n'); if(kind==='quality') return `Good,Defects,Quality\n${d.production-d.defects},${d.defects},${m.quality.toFixed(2)}%`; return `Metric,Value\nFactory Health,${m.health}\nProduction,${d.production}\nTarget,${d.target}\nEnergy kWh,${Math.round(m.energy)}\nCost INR,${Math.round(m.cost)}\nQuality,${m.quality.toFixed(2)}\nAlerts,${m.activeAlerts}`;}
function htmlReport(){const m=metrics(),d=state.data;return `<!doctype html><html><head><title>FactoryOS Report</title><style>body{font-family:Arial;padding:32px;color:#112}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccd;padding:10px}</style></head><body><h1>FactoryOS ${state.reportType}</h1><p>Generated ${new Date().toLocaleString()}</p><table><tr><th>Metric</th><th>Value</th></tr><tr><td>Factory Health</td><td>${m.health}/100</td></tr><tr><td>Production</td><td>${fmt(d.production)}</td></tr><tr><td>Energy Cost</td><td>₹${fmt(Math.round(m.cost))}</td></tr><tr><td>Quality</td><td>${m.quality.toFixed(2)}%</td></tr><tr><td>Active Alerts</td><td>${m.activeAlerts}</td></tr></table><h2>Recommendations</h2><ul>${recommendations().map(r=>`<li>${r}</li>`).join('')}</ul></body></html>`;}

document.addEventListener('click',e=>{const el=e.target.closest('[data-action]'); if(!el) return; const a=el.dataset.action;
 if(a==='auth-mode'){state.authMode=el.dataset.mode;render();}
 if(a==='login'){const r=document.getElementById('authRole'); if(r) state.role=r.value; localStorage.setItem('factoryos-role',state.role);state.authed=true;localStorage.setItem('factoryos-auth','1');state.toast='Secure session started';render();}
 if(a==='reset-password'){state.authMode='login';state.toast='Password reset link simulated';render();}
 if(a==='logout'){state.authed=false;localStorage.removeItem('factoryos-auth');render();}
 if(a==='theme'){state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('factoryos-theme',state.theme);document.documentElement.dataset.theme=state.theme;render();}
 if(a==='nav'){state.route=el.dataset.route;state.search='';state.sidebar=false;render();}
 if(a==='mobile-menu'){state.sidebar=!state.sidebar;render();}
 if(a==='select-machine'){state.selectedMachine=el.dataset.id;state.route='digital';render();}
 if(a==='add-machine'){const n=state.data.machines.length+1;state.data.machines.push({...state.data.machines[0],id:`M-${String(n).padStart(2,'0')}`,name:'New Smart Machine',x:rnd(10,88),y:rnd(20,78),status:'running',health:92,output:0,maint:['New installation logged']});state.toast='Machine added to simulator';render();}
 if(a==='mark-alerts'){state.data.alerts.forEach(x=>x.read=true);state.toast='Alerts marked read';render();}
 if(a==='reorder-inventory'){state.data.inventory.forEach(i=>{if(i.current<i.min)i.current=i.min*2.2});state.toast='Purchase suggestions converted to reorder plan';render();}
 if(a==='save-settings'){document.querySelectorAll('[data-setting]').forEach(i=>state.settings[i.dataset.setting]=i.value);state.toast='Settings saved';render();}
 if(a==='generate-report'){state.reportGenerated={type:state.reportType,at:new Date()};state.toast=`${state.reportType} generated`;render();}
 if(a==='set-report'){state.reportType=el.dataset.report;render();}
 if(a==='export-csv'){download(`factoryos-${el.dataset.kind||'export'}.csv`,csvFor(el.dataset.kind));state.toast='CSV exported';render();}
 if(a==='export-html'){download(`factoryos-${el.dataset.kind||'report'}.html`,htmlReport(),'text/html');state.toast='HTML report exported';render();}
 if(a==='print'){window.print();}
 if(a==='toast'){state.toast=el.dataset.msg||'Action completed';render();}
 if(a==='ask-suggestion'){sendChat(el.dataset.prompt);}
 if(a==='send-chat'){const input=document.getElementById('chatPrompt'); if(input&&input.value.trim())sendChat(input.value.trim());}
});
function sendChat(q){state.chat.push({who:'user',text:q});state.chat.push({who:'ai',text:aiAnswer(q)});state.route='copilot';render();setTimeout(()=>{const m=document.querySelector('.messages');if(m)m.scrollTop=m.scrollHeight;},0);}
document.addEventListener('input',e=>{const t=e.target; if(t.id==='globalSearch'){state.search=t.value;render();setTimeout(()=>document.getElementById('globalSearch')?.focus(),0);} if(t.id==='roleSelect'){state.role=t.value;localStorage.setItem('factoryos-role',state.role);state.toast='Role access updated';render();} if(t.id==='machineFilter'){state.machineFilter=t.value;render();} if(t.id==='reportType'){state.reportType=t.value;render();}});
let dragWidget=null;document.addEventListener('dragstart',e=>{const w=e.target.closest('[data-widget]');if(w)dragWidget=w.dataset.widget;});document.addEventListener('dragover',e=>{if(e.target.closest('[data-widget]'))e.preventDefault();});document.addEventListener('drop',e=>{const w=e.target.closest('[data-widget]');if(w&&dragWidget&&w.dataset.widget!==dragWidget){const arr=state.widgets;const from=arr.indexOf(dragWidget),to=arr.indexOf(w.dataset.widget);arr.splice(to,0,arr.splice(from,1)[0]);render();}});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('globalSearch')?.focus();}});
render();
